import * as React from "react";

// This is an example of a forwardRef component generated by shadcn/ui but i
// removed the styles and the other props to make it simple.
const Input = React.forwardRef<HTMLInputElement, React.ComponentProps<"input">>(
  ({ className, type, ...props }, ref) => {
    return <input type={type} className={className} ref={ref} {...props} />;
  },
);
Input.displayName = "Input";

export { Input };
